# Generated by Django 3.0.1 on 2020-01-26 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auto_20200125_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='user',
        ),
    ]
