# Generated by Django 3.0.1 on 2020-01-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_remove_offer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='found_at',
        ),
        migrations.AddField(
            model_name='offer',
            name='service_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
