# Generated by Django 3.0.1 on 2020-01-28 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0008_auto_20200128_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_percentage_change',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
